enum Schema {
    static let activity = "activity"
    static let dropInSessions =  "dropin_sessions"
    static let dropInSessionSlots = "dropin_session_slots"
    static let event = "events"
    static let eventDay = "event_days"
    static let job = "jobs"
    static let lastUpdated = "last_updated"
    static let location = "locations"
    static let locationCategory = "locationCategories"
    static let presentation = "presentations"
    static let slot = "slots"
    static let speaker = "speakers"
    static let sponsor = "sponsors"
    static let sponsorLevel = "sponsor_level"
    static let tokens = "tokens"
    static let user = "users"
    static let userToken = "user_tokens"
    static let userReview = "user_reviews"
}
